apiVersion: v1
kind: Service
metadata:
  name: redisbank
  labels:
    app: redisbank
spec:
  ports:
  - port: 8080
    name: redisbank
    protocol: TCP
  selector:
    app: redisbank
  type: LoadBalancer
